Feat/ade 500/add servlet restful get endpoint
agiledigital-labs/confluence-plugin-idea-search pull request #20
Opened 2020-11-27 02:10 UTC by shouvSarker

2020-11-27 04:00 UTC, SamMurphyDev requested changes

2020-11-27 04:00 UTC, SamMurphyDev commented on .github/workflows/on-push-maven-integration-test.yml
> +# Integration tests are run with preloaded test confluence instance. For more information, see: https://developer.atlassian.com/server/framework/atlassian-sdk/create-test-data-and-a-test-fixture .
Wrap text please

2020-11-27 04:47 UTC, shouvSarker commented on .github/workflows/on-push-maven-integration-test.yml
> +        # This may through some null pointer exceptions after confluence shuts down and Tomcat stops. Error logs on confluence shut down has been a known issue.
Updated, thanks for picking up!

2020-11-27 04:54 UTC, shouvSarker commented on pom.xml
> +                        <Import-Package>org.springframework.osgi.*;resolution:="optional", org.eclipse.gemini.blueprint.*;resolution:="optional", *</Import-Package>
Ran prettier and updated!

2020-11-27 04:54 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/dao/AoFedexIdea.java
> +    @AutoIncrement
Updated.

2020-11-27 05:00 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +  HttpServletRequest mockRequest;
Updated

2020-11-27 05:04 UTC, dspasojevic commented on pom.xml
> +            >au.com.agiledigital.idea_search,</Export-Package>
This formatting looks strange. What is causing the jitter between PRs?

2020-11-27 05:04 UTC, dspasojevic commented on src/main/java/au/com/agiledigital/idea_search/service/DefaultFedexIdeaService.java
> +  public List<String> techList() {
For methods that hit a database, lets use a verb - `queryTechList`.

2020-11-27 05:05 UTC, dspasojevic commented on src/main/java/au/com/agiledigital/idea_search/servlet/TechnologyServlet.java
> +import com.google.gson.*;
What is deciding whether to import with `*` here?

2020-11-27 05:05 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +    String expected = String.valueOf(this.gson.toJson(Arrays.asList("perl")));
Thanks for catching it, the toJson call returns a string, so basically, this was stringifying a string. :facepalm: 

Updated and took `String.valueOf` out.

2020-11-27 05:06 UTC, dspasojevic commented on src/main/java/au/com/agiledigital/idea_search/servlet/TechnologyServlet.java
> +    resp.setContentType("application/json");
Do you get access to this content type and encoding as constants in a library somewhere? e.g. javax.servlet.http

2020-11-27 05:07 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServlete2eTest.java
> +  HttpServletRequest mockRequest;
Updated.

2020-11-27 05:09 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServlete2eTest.java
> +    String expected = String.valueOf(this.gson.toJson(Arrays.asList("angular", "perl", "python")));
Updated.

2020-11-27 05:09 UTC, robinMcA commented on src/main/java/au/com/agiledigital/idea_search/service/DefaultFedexIdeaService.java
> +    return fedexIdeaDao.techDaoList().stream().collect(Collectors.toSet());
This should already be a list of Strings?

2020-11-27 05:09 UTC, robinMcA commented on src/test/java/au/com/agiledigital/idea_search/dao/IdeaDaoTest.java
> +  @Test
comments/what is the test doing

2020-11-27 05:11 UTC, shouvSarker commented on src/test/java/it/au/com/agiledigital/idea_search/servlet/TechnologyServletTest.java
> +    HttpClient httpClient;
Updated.

2020-11-27 05:17 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServlete2eTest.java
> +      final AoFedexTechnology seedAoFedexTechnologyPython = em.create(AoFedexTechnology.class);
Removed `final`

2020-11-27 05:18 UTC, shouvSarker commented on .github/workflows/on-push-maven-integration-test.yml
> +# Integration tests are run with preloaded test confluence instance. For more information, see: https://developer.atlassian.com/server/framework/atlassian-sdk/create-test-data-and-a-test-fixture .
Wrapped.

2020-11-27 05:27 UTC, dspasojevic commented on src/test/java/au/com/agiledigital/idea_search/service/IdeaServiceTest.java
> +    List<String> expected = Collections.emptyList();
Rather name this `noTechs` and the others in a similar informative way. However, these tests are the same thing but with different data, so it should be a data-driven test.

Please rewrite.

2020-11-27 05:33 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/service/DefaultFedexIdeaService.java
> +    return fedexIdeaDao.techDaoList().stream().distinct().collect(Collectors.toList());
Is there a performance difference between `distinct` and `toSet`?

2020-11-27 05:34 UTC, dspasojevic commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +    Mockito.when(mockResponse.getWriter()).thenReturn(pw);
Is there a wrapper that simplifies this?

2020-11-27 05:34 UTC, dspasojevic commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +  private FedexIdeaDao fedexIdeaDao = Mockito.mock(FedexIdeaDao.class);
Are your tests isolated when using a shared mock?

2020-11-27 05:34 UTC, dspasojevic commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +  HttpServletResponse mockResponse;
Do not use default visibility.

2020-11-27 05:35 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/service/DefaultFedexIdeaService.java
> +  public List<String> techList() {
Updated.

2020-11-27 05:37 UTC, dspasojevic commented
What is ` src/test/resources/generated-test-resources.zip ` and why is it in `src/test`?

2020-11-27 05:42 UTC, SamMurphyDev commented on src/main/java/au/com/agiledigital/idea_search/service/DefaultFedexIdeaService.java
> +    return fedexIdeaDao.techDaoList().stream().distinct().collect(Collectors.toList());
From my quick bit a of reading, `toSet` uses more memory because it uses a HashSet under the hood, as `distinct` uses an ArrayList. The generally community answer is with so little amount items in the stream, there's not going to be a sizeable improvement either way you go. https://stackoverflow.com/questions/48994190/stream-collectcollectors-toset-vs-stream-distinct-collectcollectors-t?noredirect=1&lq=1

2020-11-27 05:48 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/servlet/TechnologyServlet.java
> +import com.google.gson.*;
Thanks for catching this. Made it specific with `import com.google.gson.Gson;`, similar to other Gson imports.

2020-11-27 06:14 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/servlet/TechnologyServlet.java
> +    resp.setContentType("application/json");
In `javax.servlet.http` there aren't any constants for this, but there are other libraries.

Using `standardCharsets.charType.name()` for charset from  https://docs.oracle.com/javase/7/docs/api/java/nio/charset/StandardCharsets.html

And `javax.ws.rs.core.MediaType` for content type.

2020-11-27 06:17 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +  HttpServletResponse mockResponse;
Updated with `private`

2020-11-27 06:32 UTC, shouvSarker commented
> What is `src/test/resources/generated-test-resources.zip` and why is it in `src/test`?

One of the ways to create test data and test fixture for confluence plugin tests is to use a preloaded confluence instance. A confluence instance can be started in debug mode, populated with data through interaction, zipped and then used as a fixture file. Modifications can be made by starting the instance in debug mode and interacting with it. 

However, this has limitations, as in not offering full control and clarity over the fixture. Traditional integration test with selenium or other tools would be more powerful. 

Atlassian suggests this as a way to set up fixtures for integration test.
https://developer.atlassian.com/server/framework/atlassian-sdk/create-test-data-and-a-test-fixture/

2020-11-29 21:11 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/service/DefaultFedexIdeaService.java
> +    return fedexIdeaDao.techDaoList().stream().distinct().collect(Collectors.toList());
Thanks! Keeping distinct for this case.

2020-11-29 21:24 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/dao/FedexIdeaDao.java
> +    public List<String> techDaoList(){
Updated.

2020-11-29 21:24 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/servlet/TechnologyServlet.java
> +import com.google.gson.*;
Updated.

2020-11-29 21:25 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/service/DefaultFedexIdeaService.java
> +    return fedexIdeaDao.techDaoList().stream().collect(Collectors.toSet());
Updated with a list of strings.

2020-11-30 00:22 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +  private FedexIdeaDao fedexIdeaDao = Mockito.mock(FedexIdeaDao.class);
Modified to mock per test instead of using shared mock.

2020-11-30 00:22 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/service/IdeaServiceTest.java
> +    List<String> expected = Collections.emptyList();
Rewritten

2020-11-30 00:23 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/dao/IdeaDaoTest.java
> +  @Test
Commented

2020-11-30 00:23 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/dao/FedexIdeaDao.java
> +    public List<String> techDaoList(){
Moved to dao

2020-11-30 01:18 UTC, shouvSarker commented
> What is `src/test/resources/generated-test-resources.zip` and why is it in `src/test`?

Updated readme with details about generated-test-resources.

2020-11-30 01:47 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +    Mockito.when(mockResponse.getWriter()).thenReturn(pw);
There are different ways to write this but haven't found a wrapper in mockito that can simplify this significantly.

There is a mock print writer, but `getWriter()` is a method called on response servlet object, which is mocked in this case. Trying to pass a mock printWriter throws null pointer error, possibly because how it is invoked. Hence passing in a `printwriter` when `getWriter` is called, and then verifying on the printWriter if the expected response was written.

2020-11-30 03:02 UTC, shouvSarker commented on pom.xml
> +            >au.com.agiledigital.idea_search,</Export-Package>
Updated and made overall indentation consistent. Different XML linting or manual edits could have caused it. Running Prettier after the current version doesn't modify it further.

2020-11-30 03:20 UTC, SamMurphyDev commented on pom.xml
> +                        <!--                        </Atlassian-Plugin-Key>-->
Is this meant to be commented out. If is it, can it be removed

2020-11-30 03:20 UTC, SamMurphyDev commented on src/main/java/au/com/agiledigital/idea_search/dao/FedexIdeaDao.java
> +  }
I feel like inverting this if statement would flow better.

```suggestion
  private String getUsername(String userKey) {
    if (userKey != null) {
      ConfluenceUser user =
        this.userAccessor.getUserByKey(new UserKey(userKey));
      return user == null ? null : user.getLowerName();
    }
    
    return null;
  }
```

2020-11-30 03:20 UTC, SamMurphyDev commented on src/test/java/au/com/agiledigital/idea_search/dao/IdeaDaoTest.java
> +    List<String> multipleDaoTech = Arrays.asList("perl", "python");
This is only used once in this function. Maybe better to put this inline on line 97

2020-11-30 03:20 UTC, SamMurphyDev commented on src/test/java/au/com/agiledigital/idea_search/service/IdeaServiceTest.java
> +  private static List<String> multipleTech = Arrays.asList(
Any reason why these are static?

2020-11-30 03:33 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/dao/IdeaDaoTest.java
> +    List<String> multipleDaoTech = Arrays.asList("perl", "python");
This is the expected result of this test, listed it as a variable separately to increase readability and a separate point of modification. But open to ideas and suggestions about how best to structure expected fixture.

2020-11-30 03:36 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/service/IdeaServiceTest.java
> +  private static List<String> multipleTech = Arrays.asList(
Parameterized require data to be supplied in a static context. hence they are declared as static here. An alternative way is to supply the data directly instead of having variables.

2020-11-30 03:36 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/dao/FedexIdeaDao.java
> +  }
Updated

2020-11-30 03:36 UTC, shouvSarker commented on pom.xml
> +                        <!--                        </Atlassian-Plugin-Key>-->
Yes, removed.

2020-11-30 23:33 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/dao/IdeaDaoTest.java
> +  FedexIdeaDao ideaDao = new FedexIdeaDao(ao, userAccessor);
Isolated the test cases, so there is no class level declaration anymore.

2020-11-30 23:35 UTC, shouvSarker commented on src/test/java/it/au/com/agiledigital/idea_search/servlet/TechnologyServletTest.java
> +        servletUrl = baseUrl + "/plugins/servlet/technology";
Removed the extra variable declaration.

2020-12-01 00:16 UTC, SamMurphyDev reviewed
A couple of small nitpicks

2020-12-01 00:16 UTC, SamMurphyDev commented on src/main/java/au/com/agiledigital/idea_search/service/DefaultFedexIdeaService.java
> +  /**
Add javadoc description. See https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html for required fields

2020-12-01 00:16 UTC, SamMurphyDev commented on src/test/java/au/com/agiledigital/idea_search/dao/IdeaDaoTest.java
> +   * Istolating test cases as test data specific method call mocks are required.
Can this be changed to a `/*` comment instead of `/**` as this is not JavaDoc.

2020-12-01 00:16 UTC, SamMurphyDev commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +   * Istolating test cases as test data specific method call mocks are required.
```suggestion
   * Isolating test cases as test data specific method call mocks are required.
```

2020-12-01 00:16 UTC, SamMurphyDev commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +  /**
Can this be changed to a `/*` comment instead of `/**` as this is not JavaDoc

2020-12-01 00:16 UTC, SamMurphyDev commented on src/test/java/au/com/agiledigital/idea_search/dao/IdeaDaoTest.java
> +   * Istolating test cases as test data specific method call mocks are required.
```suggestion
   * Isolating test cases as test data specific method call mocks are required.
```

2020-12-01 00:22 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/dao/IdeaDaoTest.java
> +   * Istolating test cases as test data specific method call mocks are required.
Changed!

2020-12-01 00:23 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +   * Istolating test cases as test data specific method call mocks are required.
Thanks, modified!

2020-12-01 00:24 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/servlet/TechnologyServletUnitTest.java
> +  /**
Changed to `/*`

2020-12-01 00:24 UTC, shouvSarker commented on src/test/java/au/com/agiledigital/idea_search/dao/IdeaDaoTest.java
> +   * Istolating test cases as test data specific method call mocks are required.
Updated spelling!

2020-12-01 00:31 UTC, shouvSarker commented on src/main/java/au/com/agiledigital/idea_search/service/DefaultFedexIdeaService.java
> +  /**
Added!

2020-12-01 00:35 UTC, SamMurphyDev approved these changes
Looks good, well done

2020-12-01 00:40 UTC, merged

2021-01-11 02:52 UTC, robinMcA commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/agiledigital-labs/confluence-plugin-idea-search/releases/tag/v1.2.0)
- `v1.2.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: